version: '3.9'
services:
    lb:
        image: haproxy
        ports:
            - '8081:8080'
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    web1:
        image: nodeserver
        environment:
            - port=3001
    web2:
        image: nodeserver
        environment:
            - port=3002
