version: "3.9"
services:
  web1:
    image: nodeserver
    environment:
      - port=3001
  web2:
    image: nodeserver
    environment:
      - port=3002
  proxyserver:
    image: wslab
    ports:
      - "8081:80"
